### ISSUE TITLE
amis-editor怎么本地运行起来？

### ISSUE THREAD

**Issue by rodchen-king** [fex-team/amis-editor#14]
amis-editor怎么本地运行起来？

**Comment by 2betop** [comment]
看 readme吧，刚补充了。

**Comment by rodchen-king** [comment]
> 看 readme吧，刚补充了。

npm run dev的默认端口是什么？不是8080吧

**Comment by 2betop** [comment]
看 package.json 里面的 start script。

```
fis3 server start --www ./public --port 8082 --no-daemon
```

**Comment by yangangzhang** [comment]
> amis-editor怎么本地运行起来？

您好，editor本地起来了吗？我这里有些依赖下载不下载，起不来

**Comment by 2betop** [comment]
什么依赖下载不下来，已经没有私有仓库了

**Comment by yangangzhang** [comment]
> 什么依赖下载不下来，已经没有私有仓库了
node-version：10.16.0
使用npm install，这些问题（部分截图）：
![image](https://user-images.githubusercontent.com/20433039/89749534-af8aa680-dafa-11ea-8f95-8c182628e72a.png)

**Comment by yooshayun** [comment]
一样的报错....node版本降到了10也不行

**Comment by jiabing-china** [comment]
请问解决了吗？
