### ISSUE TITLE
通过npm包的方式引入时控制台报错

### ISSUE THREAD

**Issue by feizhen** [fex-team/amis-editor#21]
![image](https://user-images.githubusercontent.com/11854027/88753367-8ed36000-d18e-11ea-8f30-68c9e0b62b99.png)

**Comment by feizhen** [comment]
不影响使用，但是这个报错有时候挺烦人的，麻烦请教一下如何清除

**Comment by hq5544** [comment]
我也是。
按照官方加过插件，dev 模式没问题，但是生产环境还是有问题。
https://github.com/microsoft/monaco-editor-webpack-plugin/issues/32

**Comment by feizhen** [comment]
主要是，通过monaco-editor-webpack-plugin插件会额外打包worker 文件到publicPath，还需要指定 `MonacoEnvironment.getWorkerUrl` 来获取这些个worker文件

![image](https://user-images.githubusercontent.com/11854027/90003725-11980700-dcc7-11ea-9ada-94760aaaf5e6.png)
