### ISSUE TITLE
找不到自定义的渲染器

### ISSUE THREAD

**Issue by feizhen** [fex-team/amis-editor#22]
1. 使用当前仓库的例子自定义了一个编辑器和一个渲染器
2. 然后引入编辑器和渲染器，编辑器会报错提示找不到对应的渲染器
![image](https://user-images.githubusercontent.com/11854027/88793543-87807680-d1cf-11ea-8d14-9d073455fc08.png)

![image](https://user-images.githubusercontent.com/11854027/88793562-8f401b00-d1cf-11ea-9c87-74154831d0b9.png)

**Comment by 2betop** [comment]
自己检查吧，至少这个项目是跑起来了。
![image](https://user-images.githubusercontent.com/2698393/88794149-99164e00-d1d0-11ea-918a-e2be2509a011.png)
![image](https://user-images.githubusercontent.com/2698393/88794170-9fa4c580-d1d0-11ea-9f36-49913503d216.png)

**Comment by feizhen** [comment]
好的，可能和webpack的加载方式也有一定的联系，重新安装amis-editor之后就好了，感谢
