### ISSUE TITLE
关于 API的 adaptor

### ISSUE THREAD

**Issue by danmaidesenling** [fex-team/amis-editor#29]
return {
	...payload,
	items: payload.data.page.content,
	total:payload.data.page.total
}
	
type 是 crud，
我的API的格式：

{
data: page{
content:[{},{}]
total:
}

}

所以我用上面的 adaptor，但是未生效；

type": "crud",
		"draggable": true,
		"api": {
			"method": "post",
			"url": "https://us-dev-mycis.testNg.org/testService/public/api/urlRegisters/queryForm?pageSize=5000&pageNo=0&total=0",
			"adaptor":"return {...payload,data.items: payload.data.page.content,data.total:payload.data.page.total}"
		  }

**Comment by danmaidesenling** [comment]
have resovled

**Comment by slindaqiu** [comment]
请问怎么解决的？特别是怎么处理，界面提示错误信息：data.items必粗是数组?
