### ISSUE TITLE
安装后打开报错

### ISSUE THREAD

**Issue by Rock2018** [fex-team/amis-editor#30]
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (npm.js:32392)
    at Object.useEffect (npm.js:32435)
    at Layout (npm.js:121459)
    at renderWithHooks (npm.js:16896)
    at mountIndeterminateComponent (npm.js:18978)
    at beginWork (npm.js:19583)
    at performUnitOfWork (npm.js:23270)
    at workLoop (npm.js:23310)
    at HTMLUnknownElement.callCallback (npm.js:4107)
    at Object.invokeGuardedCallbackDev (npm.js:4157)
npm.js:21075 The above error occurred in the <Layout> component:
    in Layout
    in Themeable(Layout) (created by _class)
    in _class (created by inject-_class-with-store)
    in inject-_class-with-store (created by Context.Consumer)
    in Route (created by _class)
    in Switch (created by _class)
    in Suspense (created by _class)
    in div (created by _class)
    in Router (created by HashRouter)
    in HashRouter (created by _class)
    in _class (created by default_1)
    in Provider (created by default_1)
    in default_1

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ npm.js:21075
npm.js:32392 Uncaught (in promise) Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (npm.js:32392)
    at Object.useEffect (npm.js:32435)
    at Layout (npm.js:121459)
    at renderWithHooks (npm.js:16896)
    at mountIndeterminateComponent (npm.js:18978)
    at beginWork (npm.js:19583)
    at performUnitOfWork (npm.js:23270)
    at workLoop (npm.js:23310)
    at renderRoot (npm.js:23393)
    at performWorkOnRoot (npm.js:24300)

安装完amis-editor 报错

**Comment by Rock2018** [comment]
node version is v12.18.3

**Comment by Rock2018** [comment]
已经解决

**Comment by Coodool** [comment]
请问是怎么解决的呢？ @Rock2018

**Comment by cx-emerge** [comment]
`package.json`
```json
{
	...
	"resolutions": {
		"amis/react": "17.0",
		"amis/react-dom": "17.0",
		"amis/monaco-editor": "0.30",
		"amis-editor/react": "17.0",
		"amis-editor/react-dom": "17.0"
	},
	...
}
```

**Comment by ZephyrTan** [comment]
> `package.json`
> 
> ```json
> {
> 	...
> 	"resolutions": {
> 		"amis/react": "17.0",
> 		"amis/react-dom": "17.0",
> 		"amis/monaco-editor": "0.30",
> 		"amis-editor/react": "17.0",
> 		"amis-editor/react-dom": "17.0"
> 	},
> 	...
> }
> ```

我按照这个方法还是不行呢

**Comment by ZephyrTan** [comment]
> 已经解决


> 已经解决

请问怎么解决的？我也遇到这个问题，还找不到原因
