### ISSUE TITLE
The Renderer with name "myrenderer" not found

### ISSUE THREAD

**Issue by arenaswan** [fex-team/amis-editor#34]
#22 同一个问题，其他均正常，项目也能跑起来，自定义的Renderer能正常渲染，但是自定义编辑组件，加载@RendererEditor就会报错，报错堆栈如下
"Error: The Renderer with name "myrenderer" not found!
    at http://localhost:8000/vendors~p__Test~p__editor~p__page.js:45:1598
    at Module../src/components/Anole/editor/MyRendererEditor.tsx 
    at __webpack_require__ 
    at fn 
    at Module../src/pages/page/index.tsx 
    at __webpack_require__ 
    at fn

**Comment by 2betop** [comment]
检查：

* editor 版本是不是最新
* 是不是存在多个 amis 版本，editor 里面用的如不是注册时用的同一个版本就会有问题。

**Comment by arenaswan** [comment]
确实是由于多个amis版本问题导致，改过来后就好了，完美解决，感谢！！
