### ISSUE TITLE
使用renderAmis加载组件后页面没有样式。

### ISSUE THREAD

**Issue by KunCho** [fex-team/amis-editor#36]
使用renderAmis加载组件后页面没有样式，这种情况需要怎么解决。

**Comment by 2betop** [comment]
你得引入样式表

**Comment by gaving-mx** [comment]
<link rel="stylesheet" href="font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="bootstrap/dist/css/bootstrap.css" />
        
        <link rel="stylesheet" href="amis/lib/themes/default.css" />
        <link rel="stylesheet" href="amis-editor/dist/style.css" />
