### ISSUE TITLE
树节点增删改查问题

### ISSUE THREAD

**Issue by unsad** [fex-team/amis-editor#6]
请问一下编辑嵌套层次较深的节点属性时，是如何回改到原有的JSON的？

**Comment by 2betop** [comment]
json 每一次层都加个唯一 ID

**Comment by unsad** [comment]
> json 每一次层都加个唯一 ID

感谢回复！加ID我能理解，我的疑惑在于拿到ID后回查的过程。每次点击编辑区的渲染器时，都是从JSON对象最外层递归查找的吗？这样好像会有性能问题，还是有更合适的方案？有对JSON对象拆分成2维表再重组的过程吗？另外就是我看amis源码的schemarender的renderchild并没有加ID的动作，就是单纯的递归渲染，amis-editor没有复用amis的schemarender渲染编辑区吗？谢谢解惑！

**Comment by 2betop** [comment]
目前就是递归查找，json 应该不会到有性能问题吧，至少目前还没感觉。id 是编辑器加的，amis 里面没加，但是渲染还是复用的 amis 的 schemaRenderer，利用 resolveEditor 那个口子，在渲染渲染器的前面改成渲染包了一层编辑器。

**Comment by unsad** [comment]
> 目前就是递归查找，json 应该不会到有性能问题吧，至少目前还没感觉。id 是编辑器加的，amis 里面没加，但是渲染还是复用的 amis 的 schemaRenderer，利用 resolveRenderer 那个口子，在渲染渲染器的前面改成渲染包了一层编辑器。

原来如此。那就是JSON树进来后先由编辑器递归一遍加上ID，父子关系这样的标记，再把加工过的JSON树进schemarenderer渲染，所有的渲染器包装一层处理编辑关系的高阶组件这样吗？那这样还有一个问题，JSON树递归加上ID的过程是如何识别这个字段是渲染器的，用带type字段的对象判断的话像page的body这样可能是string的字段就行不通了？

**Comment by 2betop** [comment]
是类似于高阶组件。

JSON 节点是不是渲染器，这个是 amis 里面的逻辑，那里面在注册渲染器的时候是用正则指定的，这里面有说明 https://baidu.github.io/amis/docs/sdk#%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86

你说的容器里面的成员可以是字符串的问题，这个在对应的容器组件里面做了处理，这个在 didMount 里面会把那些容器里面的 string 替换成 {type: 'tpl', tpl: 'raw string'}。 这样就能加 id 了，然后可以定位。

**Comment by unsad** [comment]
> 是类似于高阶组件。
> 
> JSON 节点是不是渲染器，这个是 amis 里面的逻辑，那里面在注册渲染器的时候是用正则指定的，这里面有说明 https://baidu.github.io/amis/docs/sdk#%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86
> 
> 你说的容器里面的成员可以是字符串的问题，这个在对应的容器组件里面做了处理，这个在 didMount 里面会把那些容器里面的 string 替换成 {type: 'tpl', tpl: 'raw string'}。 这样就能加 id 了，然后可以定位。

咦，加ID的时机不是在JSON进入渲染器之前由编辑器做的吗？我的理解是在JSON进入到渲染器之前做递归渲染之前会由编辑器先递归一遍加上ID和父子关系，这一步还没有渲染吧，didMount也无效啊。还是说我对加ID的时机理解有误？

**Comment by 2betop** [comment]
没错，didMount 还可以补加

**Comment by unsad** [comment]
对那还是回到了上面的问题，既然JSON递归加ID是在进入渲染器之前，那就没有用正则匹配判断加ID的字段吧。比如page有toolbar,body,title等等字段，那递归的时候是怎么知道toolbar和body是需要被加上ID，title不用加的呢

**Comment by 2betop** [comment]
容器节点本身是渲染之前加的，比如：

```json
{
   "type": "page",
  "title": "test",
  "body": ["第一段文字", {"type": "tpl", "tpl": "第二段文字"}]
}
```

type 为 page 和 tpl 的节点渲染之前就加了 id， 然后开始渲染。  PageEditor 和 第二段的 TplEditor 开始渲染了。然后 PageEditor 的 didMount 里面，他发现自己的容器 'aside'、'body' 或者 'toolbar'里面有纯字符串成员，然后就 body 篡改成  `[{"type": "tpl", "tpl": "第一段文字"}, {"type": "tpl", "tpl": "第二段文字"}]` 然后再次渲染它的孩子节点 。  这样第一段文字的编辑器(Component) 也就开始渲染了。

**Comment by unsad** [comment]
> 容器节点本身是渲染之前加的，比如：
> 
> ```json
> {
>    "type": "page",
>   "title": "test",
>   "body": ["第一段文字", {"type": "tpl", "tpl": "第二段文字"}]
> }
> ```
> 
> type 为 page 和 tpl 的节点渲染之前就加了 id， 然后开始渲染。 PageEditor 和 第二段的 TplEditor 开始渲染了。然后 PageEditor 的 didMount 里面，他发现自己的容器 'aside'、'body' 或者 'toolbar'里面有纯字符串成员，然后就 body 篡改成 `[{"type": "tpl", "tpl": "第一段文字"}, {"type": "tpl", "tpl": "第二段文字"}]` 然后再次渲染它的孩子节点 。 这样第一段文字的编辑器(Component) 也就开始渲染了。

"type 为 page 和 tpl 的节点渲染之前就加了 id"，篡改我理解了，我的问题其实就是这个。。这个之前是怎么加上去的？

**Comment by 2betop** [comment]
这个啥是怎么加上去的？你写清楚点，我没理解你说的是啥。

**Comment by unsad** [comment]
> 这个啥是怎么加上去的？你写清楚点，我没理解你说的是啥。

就你说过的这句话："**type 为 page 和 tpl 的节点渲染之前就加了 id**"。之前的id是怎么判断能加到type为page和type为tpl的节点呢？如果再多一个带type的非渲染器对象，这个id会加上去吗？关键就是想知道你说的这个"之前"加id的递归判断逻辑。

**Comment by 2betop** [comment]
这个好说啊，凡事类型为 object 的都加，管它能不能对应到渲染器

**Comment by unsad** [comment]
> 这个好说啊，凡事类型为 object 的都加，管它能不能对应到渲染器

哦哦原来是这样。那我再理一下流程，就是JSON先进入编辑器，递归给所有对象加上ID，然后再进入渲染器渲染，由Editor这层容器（不同的渲染器有各自的判断逻辑？）判断自己的容器字段是不是有字符串，是就篡改成对象的形式顺便加上ID同步回JSON对象，同时由Editor这层记录自己的ID。然后点击的时候根据这个ID到JSON对象中找到对应的对象，再丢到属性编辑器里渲染供用户修改？

**Comment by 2betop** [comment]
对

**Comment by unsad** [comment]
> 对

了解了，感谢解答🙏
