### ISSUE TITLE
请问一下编辑模式下button的onAction是如何拦截的

### ISSUE THREAD

**Issue by unsad** [fex-team/amis-editor#8]
编辑模式下，点击配置dialog的弹窗会被阻止，但button根据schema渲染应该会绑定click弹出dialog。请问是在哪里拦截这个click事件的呢

**Comment by 2betop** [comment]
react 的事件都是代理到 body 的，貌似。所以，你自己写个 previewDom.addEventlistener 然后在里面阻止冒泡就可以了
